// Package formula はリリース成果物から Homebrew formula を生成する。
//
// goreleaser の brews セクションは非推奨で、後継の homebrew_casks は
// cask のため shell/pwt.sh のような付随ファイルを安定したパスに置けない。
// formula の生成だけを自前で持ち、ビルドとリリースは goreleaser に任せる。
package formula

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strings"
	"text/template"
)

// requiredPlatforms は formula が必ず持つべき os/arch の組み合わせ。
var requiredPlatforms = []string{
	"darwin/arm64",
	"darwin/amd64",
	"linux/arm64",
	"linux/amd64",
}

// Asset はリリースアーカイブ 1 つ分。
type Asset struct {
	OS     string // darwin / linux
	Arch   string // arm64 / amd64
	File   string
	SHA256 string
}

// Platform は "os/arch" 形式のキー。
func (a Asset) Platform() string { return a.OS + "/" + a.Arch }

// Input は formula の生成に必要な情報。
type Input struct {
	Repo    string // owner/name
	Tag     string // v0.1.0
	Version string // 0.1.0
	Assets  []Asset

	byPlatform map[string]Asset
}

// URLFor は指定プラットフォームのダウンロード URL を返す。
func (in Input) URLFor(platform string) string {
	return fmt.Sprintf("https://github.com/%s/releases/download/%s/%s",
		in.Repo, in.Tag, in.byPlatform[platform].File)
}

// SHAFor は指定プラットフォームのチェックサムを返す。
func (in Input) SHAFor(platform string) string {
	return in.byPlatform[platform].SHA256
}

// ParseChecksums は goreleaser の checksums.txt を読む。
// 各行は "<sha256>  <filename>" 形式で、tar.gz 以外の行は無視する。
func ParseChecksums(r io.Reader) ([]Asset, error) {
	var assets []Asset

	sc := bufio.NewScanner(r)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) != 2 {
			return nil, fmt.Errorf("unexpected line in checksums: %q", line)
		}
		sum, file := fields[0], fields[1]
		if !strings.HasSuffix(file, ".tar.gz") {
			continue
		}

		goos, goarch, err := platformOf(file)
		if err != nil {
			return nil, err
		}
		assets = append(assets, Asset{OS: goos, Arch: goarch, File: file, SHA256: sum})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}

	sort.Slice(assets, func(i, j int) bool { return assets[i].File < assets[j].File })

	return assets, nil
}

// platformOf は <name>_<version>_<os>_<arch>.tar.gz から os と arch を取り出す。
func platformOf(file string) (goos, goarch string, err error) {
	base := strings.TrimSuffix(file, ".tar.gz")
	parts := strings.Split(base, "_")
	if len(parts) < 3 {
		return "", "", fmt.Errorf("cannot determine platform from %q", file)
	}
	return parts[len(parts)-2], parts[len(parts)-1], nil
}

// Render は formula の内容を返す。必須プラットフォームが欠けている場合はエラー。
func Render(in Input) (string, error) {
	if in.Repo == "" || in.Tag == "" || in.Version == "" {
		return "", fmt.Errorf("repo, tag and version are required")
	}

	in.byPlatform = make(map[string]Asset, len(in.Assets))
	for _, a := range in.Assets {
		in.byPlatform[a.Platform()] = a
	}
	for _, p := range requiredPlatforms {
		if _, ok := in.byPlatform[p]; !ok {
			return "", fmt.Errorf("missing release asset for %s", p)
		}
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, in); err != nil {
		return "", err
	}

	return b.String(), nil
}

var tmpl = template.Must(template.New("formula").Parse(`# This file is generated by tools/formula. DO NOT EDIT.
class Pwt < Formula
  desc "Thin wrapper around git worktree with shared-asset syncing"
  homepage "https://github.com/{{ .Repo }}"
  version "{{ .Version }}"
  license "MIT"

  on_arm do
    on_macos do
      url "{{ .URLFor "darwin/arm64" }}"
      sha256 "{{ .SHAFor "darwin/arm64" }}"
    end
    on_linux do
      url "{{ .URLFor "linux/arm64" }}"
      sha256 "{{ .SHAFor "linux/arm64" }}"
    end
  end

  on_intel do
    on_macos do
      url "{{ .URLFor "darwin/amd64" }}"
      sha256 "{{ .SHAFor "darwin/amd64" }}"
    end
    on_linux do
      url "{{ .URLFor "linux/amd64" }}"
      sha256 "{{ .SHAFor "linux/amd64" }}"
    end
  end

  def install
    bin.install "pwt"
    pkgshare.install "shell/pwt.sh"
    generate_completions_from_executable(bin/"pwt", "completion")
  end

  def caveats
    <<~EOS
      pwt works as-is. To move between worktrees with ` + "`pwt switch`" + `,
      add this to your ~/.zshrc (or ~/.bashrc):

        source "#{opt_pkgshare}/pwt.sh"

      Without it, move with:

        cd "$(pwt path 2)"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pwt --version")
  end
end
`))
